[project]
name = "backend"
version = "0.1.0"
description = "Backend for the IoT Conference project"
readme = "README.md"
authors = [{ name = "Ponche", email = "josueguevara792@gmail.com" }]
requires-python = ">=3.12"

dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.3",
    "flask-cors>=6.0.5",
    "pymongo>=4.18.2",
]

[dependency-groups]
dev = ["ty>=0.0.84"]

[tool.uv]
package = false
